### ISSUE TITLE
zoom factor for height and width

### ISSUE THREAD

**Issue by njuh0** [mwydmuch/ZoomVideoComposer#13]
add zoom factor separately for height and width please

**Comment by mwydmuch** [comment]
Hi @njuh0, I don't find it very useful since the dimensions of a video need to be fixed. Different horizontal and vertical zoom factors would require either cropping parts (larger with time) of the images or stretching/squeezing the image (more with time) on one axis to fit the frame. Not sure which one you would like to achieve. Could you say more about why you need it?

**Comment by njuh0** [comment]
I'm using ComfyUI generated 1080 x 1920 pixel images. Since the width and height are different, I guess I need to set the zoom factor separately.

**Comment by mwydmuch** [comment]
Not at all! The zoom factor is independent of image resolution. You can imagine the process of generating zoomed out images as taking the original image, scaling it down by the zoom factor (e.g., in your case, 1080 x 1920 to 540 x 960 for zoom factor = 2.0) centering, and generating the image for the empty space around to get full 1080 x 1920 image filled out. As long as the proportion of both dimensions stay the same, you don't need different zoom factors for the vertical and horizontal axis. And in most cases, you probably don't want that since as I explained in the previous message, you either need to change the resolution of the video or distort the image. 

**The script works well with any resolution of images as long as it zoom outs from the center. Don't need to provide any other parameters in this case than the zoom factor used to generate the sequence of images.** 

Here are some examples of videos generated using this script that use other resolutions of images than 1:1: 
https://www.reddit.com/r/midjourney/comments/14yv90n/zoom_out_animations_lt35_universe_trip_down_the/
